P140_Pronia/Entities/Plant.cs
namespace P140_Pronia.Entities
{
    public class Plant
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
        public string SKU { get; set; } = null!;
        public string Name { get; set; } = null!;
        public string Description { get; set; } = null!;
        public ICollection<PlantImage> PlantImages { get; set; } = null!;
        public ICollection<PlantCategory> PlantCategories { get; set; } = null!;
        public ICollection<PlantInformation> PlantInformations { get; set; } = null!;

        public Plant()
        {
            PlantImages = new List<PlantImage>();
            PlantCategories = new List<PlantCategory>();
            PlantInformations = new List<PlantInformation>();
        }

    }
}

P140_Pronia/Areas/Admin/Controllers/PlantsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using P140_Pronia.DAL;
using P140_Pronia.Entities;
using P140_Pronia.Helpers;
using P140_Pronia.ViewModels;
using System.Collections;
using System.Linq;

namespace P140_Pronia.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PlantsController : Controller
    {
        private readonly ProniaDbContext _context;
        private readonly IWebHostEnvironment _env;

        public PlantsController(ProniaDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public IActionResult Index(int page = 1)
        {
            double plantCount = _context.Plants.Include(p => p.PlantImages).AsEnumerable().Count();
            ViewBag.PageCount = Math.Ceiling(plantCount / 2);
            ViewBag.CurrentPage = page;

            IEnumerable<Plant> model = _context.Plants.Include(p => p.PlantImages).Skip((page-1)*2).Take(2).AsEnumerable();
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            PlantCreateVM model = new PlantCreateVM
            {
                Informations = await _context.Informations.ToListAsync(),
                Categories = _context.Categories.ToList()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PlantCreateVM plant)
        {
            PlantCreateVM model = new PlantCreateVM
            {
                Informations = await _context.Informations.ToListAsync(),
                Categories = _context.Categories.ToList()
            };
            if (!ModelState.IsValid) return View(model);
            Plant newPlant = new Plant();

            bool skuResult = _context.Plants.Any(p => p.SKU.ToLower() == plant.SKU.ToLower());
            if (skuResult)
            {
                ModelState.AddModelError("SKU", "SKU code is duplicated");
                return View(model);
            }
            TempData["test"] = "test";

            #region Main and hover photo
            if (!plant.MainPhoto.IsValidLength(1) || !plant.HoverPhoto.IsValidLength(1))
            {
                ModelState.AddModelError(string.Empty, "Photo size error");
                return View(model);
            }
            string mainPhotoName = await plant.MainPhoto.GeneratePhoto(_env.WebRootPath, "assets", "images", "website-images");
            PlantImage mainImage = new PlantImage
            {
                Path = mainPhotoName,
                IsMain = true
            };
            newPlant.PlantImages.Add(mainImage);

            string hoverPhotoName = await plant.HoverPhoto.GeneratePhoto(_env.WebRootPath, "assets", "images", "website-images");
            PlantImage hoverImage = new PlantImage
            {
                Path = hoverPhotoName,
                IsMain = null
            };
            newPlant.PlantImages.Add(hoverImage);

            #endregion

            #region Other photos
            foreach (var photo in plant.Photos)
            {
                if (!photo.IsValidLength(1))
                {
                    TempData["Incorrects"] += photo.FileName + ' ';
                    continue;
                }
                PlantImage other = new PlantImage
                {
                    Path = await photo.GeneratePhoto(_env.WebRootPath, "assets", "images", "website-images"),
                    Plant = newPlant,
                };
                newPlant.PlantImages.Add(other);
            }

            #endregion

            #region Categories and Informations
            foreach (int id in plant.CategoryIds)
            {
                PlantCategory category = new PlantCategory()
                {
                    CategoryId = id,
                    Plant = newPlant
                };
                newPlant.PlantCategories.Add(category);
            }

            foreach (int id in plant.InformationIds)
            {
                PlantInformation information = new PlantInformation()
                {
                    InformationId = id,
                    Plant = newPlant
                };
                newPlant.PlantInformations.Add(information);
            }
            #endregion



            newPlant.SKU = plant.SKU;
            newPlant.Name = plant.Name;
            newPlant.Price = plant.Price;
            newPlant.Description = plant.Description;

            await _context.Plants.AddAsync(newPlant);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            if (id == 0) return BadRequest();

            PlantUpdateVM model = UpdatedPlant(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, PlantUpdateVM plant)
        {
            if (id == 0) return BadRequest();
            PlantUpdateVM model = UpdatedPlant(id);
            if (!ModelState.IsValid) return View(model);

            Plant existedPlant = _context.Plants.Include(p => p.PlantCategories)
                                                .Include(p => p.PlantImages)
                                                .FirstOrDefault(p => p.Id == id)!;

            #region Category and Information
            var removableCategories = existedPlant.PlantCategories.Where(p => !plant.CategoryIds.Contains(p.CategoryId)).ToList();

            foreach (var item in removableCategories)
            {
                existedPlant.PlantCategories.Remove(item);
            }

            foreach (var categoryId in plant.CategoryIds)
            {
                if (existedPlant.PlantCategories.Any(p => p.CategoryId != categoryId))
                {
                    PlantCategory category = new PlantCategory
                    {
                        CategoryId = categoryId
                    };
                    existedPlant.PlantCategories.Add(category);
                }
            }

            var removableInformations = existedPlant.PlantInformations.Where(p => !plant.InformationIds.Contains(p.InformationId)).ToList();

            foreach (var item in removableInformations)
            {
                existedPlant.PlantInformations.Remove(item);
            }

            foreach (var informationId in plant.InformationIds)
            {
                if (existedPlant.PlantInformations.Any(p => p.InformationId != informationId))
                {
                    PlantInformation information = new PlantInformation
                    {
                        InformationId = informationId
                    };
                    existedPlant.PlantInformations.Add(information);
                }
            }
            #endregion


            var removableImages = existedPlant.PlantImages.Where(p => !plant.PlantImagesIds.Contains(p.Id)).ToList();
            foreach (var removable in removableImages)
            {
                existedPlant.PlantImages.Remove(removable);
                FileUploadExtension.DeleteImage(removable.Path, _env.WebRootPath, "assets", "images", "website-images");
            }

            if(plant.Photos is not null)
            {
                foreach (var photo in plant.Photos)
                {
                    string fileName = await photo.GeneratePhoto(_env.WebRootPath, "assets", "images", "website-images");
                    PlantImage image = new PlantImage
                    {
                        Path = fileName,
                        IsMain = false
                    };
                    existedPlant.PlantImages.Add(image);
                }
            }


            if(plant.MainPhoto is not null)
            {
                PlantImage existedImage = existedPlant.PlantImages.FirstOrDefault(p=>p.IsMain==true)!;
                string oldName = existedImage.Path;
                string fileName = await plant.MainPhoto.GeneratePhoto(_env.WebRootPath, "assets", "images", "website-images");
                existedImage.Path = fileName;

                FileUploadExtension.DeleteImage(oldName, _env.WebRootPath, "assets", "images", "website-images");
            }
            existedPlant.Name = plant.Name;
            existedPlant.Price = plant.Price;
            existedPlant.Description = plant.Description;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        PlantUpdateVM UpdatedPlant(int id)
        {
            PlantUpdateVM model = _context.Plants.Include(p => p.PlantImages)
                                                    .Include(p => p.PlantInformations)
                                                    .Include(p => p.PlantCategories)
                                                    .Select(p => new PlantUpdateVM
                                                    {
                                                        Id = p.Id,
                                                        Name = p.Name,
                                                        Price = p.Price,
                                                        Description = p.Description,
                                                        PlantImages = p.PlantImages.ToList(),
                                                        Categories = _context.Categories.ToList(),
                                                        Informations = _context.Informations.ToList(),
                                                        PlantCategories = p.PlantCategories.ToList(),
                                                        PlantInformations = p.PlantInformations.ToList(),
                                                        PlantImagesIds = p.PlantImages.Select(p => p.Id).ToList()

P140_Pronia/Controllers/PlantsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using P140_Pronia.DAL;
using P140_Pronia.Entities;
using P140_Pronia.Helpers;
using P140_Pronia.ViewModels;
using System.Diagnostics.CodeAnalysis;

namespace P140_Pronia.Controllers
{
    public class PlantsController : Controller
    {
        private readonly ProniaDbContext _context;

        public PlantsController(ProniaDbContext context)
        {
            _context = context;
        }
        public IActionResult Details(int id)
        {
            if (id == 0) return BadRequest();
            IQueryable<Plant> queryable = _context.Plants.AsNoTracking().AsQueryable();

            Plant plant = queryable
                                    .Include(p => p.PlantInformations)
                                    .ThenInclude(p => p.Information)
                                    .Include(p => p.PlantCategories)
                                    .ThenInclude(pc => pc.Category)
                                    .Include(p => p.PlantImages)
                                    .FirstOrDefault(p => p.Id == id)!;

            PlantDetailsVM model = new PlantDetailsVM
            {
                Plant = plant,
                Relateds = RelatedPlants(queryable, plant)
            };

            if (plant is null) return NotFound();
            return View(model);
        }

        public IActionResult GetPlantsPartial(IEnumerable<Plant> Plants)
        {
            return PartialView("_PlantsPv", _context.Plants.Include(p => p.PlantImages).ToList());
        }


        public IActionResult AddBasket(int id)
        {
            if (id == 0) return NotFound();
            Plant plant = _context.Plants.Include(p => p.PlantImages).FirstOrDefault(p => p.Id == id)!;
            if (plant is null) return NotFound();

            //Get cookie
            string basket = HttpContext.Request.Cookies["basket"]!;
            CookieItem cookiePlant = new CookieItem
            {
                Id = plant.Id,
                ImagePath = plant.PlantImages.FirstOrDefault(p => p.IsMain == true)?.Path,
                Name = plant.Name,
                Price = plant.Price,
                UnitPrice =plant.Price,
                Quantity = 1
            };
            BasketItem basketItem = new BasketItem();
            if (basket is null)
            {
                basketItem.CookieItems = new List<CookieItem>
                {
                    cookiePlant
                };
            }
            else
            {
                basketItem = JsonConvert.DeserializeObject<BasketItem>(basket)!;
                CookieItem existedPlant = basketItem.CookieItems.FirstOrDefault(p => p.Id == id)!;

                if (existedPlant is null)
                {
                    basketItem.CookieItems.Add(cookiePlant);
                }
                else
                {
                    existedPlant.Quantity++;
                    existedPlant.Price = plant.Price * existedPlant.Quantity;
                }
            }
            basketItem.Count = basketItem.CookieItems.Sum(ci => ci.Quantity);
            basketItem.TotalPrice = basketItem.CookieItems.Sum(ci => ci.Price);

            //Add to cookie
            string plantsStr = JsonConvert.SerializeObject(basketItem);
            HttpContext.Response.Cookies.Append("basket", plantsStr);

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult RemoveItemFromBasket(int id)
        {
            string basketStr = HttpContext.Request.Cookies["basket"];
            if (basketStr is null)
            {
                return Json(new
                {
                    Status = 404,
                    Message = "There is no basket"
                });
            }

            BasketItem basket = JsonConvert.DeserializeObject<BasketItem>(basketStr);

            CookieItem item = basket.CookieItems.FirstOrDefault(ci => ci.Id == id);
            if (item is null)
            {
                return Json(new
                {
                    Status = 404,
                    Message = "There is no item with this id"
                });
            }

            basket.CookieItems.Remove(item);

            string newBasketStr = JsonConvert.SerializeObject(basket);
            HttpContext.Response.Cookies.Append("basket", newBasketStr);

            return Json(
                new
                {
                    Status = 200,
                    Message = $"{item.Name} hase been successfully removed"
                }
                );
        }
        public IActionResult ShowBasket()
        {
            var basket = HttpContext.Request.Cookies["basket"] ?? "";
            BasketItem convertedPlant = JsonConvert.DeserializeObject<BasketItem>(basket!)!;
            return Json(convertedPlant);
        }

        private ICollection<Plant> RelatedPlants(IQueryable<Plant> plants, Plant plant)
        {
            ICollection<PlantCategory> categories = plant.PlantCategories;

            List<Plant> relateds = new List<Plant>();

            foreach (PlantCategory category in categories)
            {
                List<Plant> founds = plants.Include(p => p.PlantImages)
                                            .Include(p => p.PlantCategories).AsEnumerable()
                                                .Where(p => p.PlantCategories
                                                            .Any(pc => pc.CategoryId == category.CategoryId)
                                                             && p.Id != plant.Id
                                                             && !relateds.Contains(p, new PlantComparer()))
                                                .ToList();

                relateds.AddRange(founds);
            }
            return relateds;
        }
    }
}

P140_Pronia/Areas/Admin/Views/Plants/Create.cshtml
@model PlantCreateVM
@{
    ViewData["Title"] = "Create";
}
<div>
    <h2>
        Create Slider
    </h2>
    <form method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
        <div>
            <label asp-for="MainPhoto"></label>
            <input asp-for="MainPhoto" class="form-control" />
            <div>
                <span asp-validation-for="MainPhoto">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="HoverPhoto"></label>
            <input asp-for="HoverPhoto" class="form-control" />
            <div>
                <span asp-validation-for="HoverPhoto">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="Photos"></label>
            <input asp-for="Photos" class="form-control" />
            <div>
                <span asp-validation-for="Photos">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <div>
                <span asp-validation-for="Name">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
            <div>
                <span asp-validation-for="Price">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="Description"></label>
            <textarea asp-for="Description" rows="5" cols="60" class="form-control" ></textarea>
            <div>
                <span asp-validation-for="Description">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="SKU"></label>
            <input asp-for="SKU" class="form-control" />
            <div>
                <span asp-validation-for="SKU">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="CategoryIds"></label>
            <select asp-for="CategoryIds" class="form-select" asp-items="@(new SelectList(Model.Categories,"Id","Name"))">
            </select>
            <div>
                <span asp-validation-for="Categories">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="InformationIds"></label>
            <select asp-for="InformationIds" class="form-select" asp-items="@(new SelectList(Model.Informations,"Id","Key"))">
            </select>
            <div>
                <span asp-validation-for="InformationIds">
                </span>
            </div>
        </div>
        <div class="mt-2">
            <button type="submit" class="btn btn-outline-success">
                Create
            </button>
        </div>
    </form>
</div>

P140_Pronia/Areas/Admin/Views/Plants/Index.cshtml
@* @using Newtonsoft.Json *@
@model IEnumerable<Plant>
@{
    ViewData["Title"] = "Index";
    //Complex case
    // string incorrectsStr = TempData["Incorrects"] as string ?? "";

    // List<IFormFile> incorrects = JsonConvert.DeserializeObject<List<IFormFile>>(incorrectsStr);null coalescing
}
<div>


    <div class="table pt-3">
        @*  Complex case *@
        @*    @if (incorrects is not null)
        {
        @if (incorrects.Count > 0)
        {
        <h4 class="text-danger">
        Failed images
        </h4>
        @foreach (var item in incorrects)
        {
        <p>@item.FileName</p>
        }
        }
        } *@

        @if (TempData["Incorrects"] is not null)
        {
            <span class="text-danger">@TempData["Incorrects"]</span>
        }
        <div>
            <a asp-controller="plants" asp-action="Create" class="btn btn-success btn-rounded btn-fw">Create</a>
        </div>
        <table class="table table-dark">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Main image
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        SKU
                    </th>

                    <th>
                        Settings
                    </th>
                </tr>
            </thead>
            <tbody>
                @{
                    int count = (ViewBag.CurrentPage - 1)*2;
                }
                @foreach (Plant plant in Model)
                {
                    <tr>
                        <td>
                            @(++count)
                        </td>
                        <td>
                            <img src="~/assets/images/website-images/@plant.PlantImages.FirstOrDefault(p=>p.IsMain == true)?.Path" />
                        </td>
                        <td>
                            @plant.Name
                        </td>
                        <td>
                            @plant.Price
                        </td>
                        <td>
                            @if (plant.Description.Length > 20)
                            {
                                @(plant.Description.Substring(0, 20) + "...")
                            }
                            else
                            {
                                @(plant.Description)
                            }
                        </td>
                        <td>
                            @plant.SKU
                        </td>
                        <td>
                            <div>
                                <a asp-controller="Plants" asp-action="Detail" asp-route-id="@plant.Id" class="btn btn-info btn-rounded btn-fw">Details</a>
                                <a asp-controller="Plants" asp-action="Update" asp-route-id="@plant.Id" class="btn btn-warning btn-rounded btn-fw">Update</a>
                                <a asp-controller="Plants" id="deleteplants" asp-action="Delete" asp-route-id="@plant.Id" class="btn btn-danger btn-rounded btn-fw">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
            @for (int i = 1; i <= ViewBag.PageCount; i++)
            {
                <li class="page-item"><a class="page-link" asp-controller="Plants" asp-action="Index" asp-route-page="@i">@i</a></li>
            }

            <li class="page-item">
                <a class="page-link" href="#">Next</a>
            </li>
        </ul>
    </nav>
</div>

P140_Pronia/Areas/Admin/Views/Plants/Update.cshtml
@model PlantUpdateVM
@{
    ViewData["Title"] = "Update";
}

<div>
    <h2>
        Create Slider
    </h2>
    <form method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
        <div>
            <label asp-for="MainPhoto"></label>
            <input asp-for="MainPhoto" class="form-control" />
            <div>
                <span asp-validation-for="MainPhoto">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="HoverPhoto"></label>
            <input asp-for="HoverPhoto" class="form-control" />
            <div>
                <span asp-validation-for="HoverPhoto">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="Photos"></label>
            <input asp-for="Photos" class="form-control" />
            <div>
                <span asp-validation-for="Photos">
                </span>
            </div>
        </div>
        <div class="images d-flex">
            @foreach (var item in Model.PlantImages)
            {
                <div class="image" style="position:relative;width:200px;height:200px">
                    @if (item.IsMain != true && item.IsMain != null)
                    {
                        <button type="button" class="delete-image btn btn-outline-danger" style="position:absolute;top:10px;right:10px">X</button>
                    }
                    <img src="~/assets/images/website-images/@item.Path" style="width:100%;height:100%;object-fit:contain" />
                    <input type="hidden" name="PlantImagesIds" value="@item.Id" />
                </div>
            }

        </div>
        <div>
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <div>
                <span asp-validation-for="Name">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
            <div>
                <span asp-validation-for="Price">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="Description"></label>
            <textarea asp-for="Description" rows="5" cols="60" class="form-control"></textarea>
            <div>
                <span asp-validation-for="Description">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="CategoryIds"></label>
            <select asp-for="CategoryIds" class="form-select">
                @foreach (var category in Model.Categories)
                {

                    @if (Model.PlantCategories.Any(p => p.CategoryId == category.Id))
                    {
                        <option value="@category.Id" selected>@category.Name</option>

                    }
                    else
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                }
            </select>
            <div>
                <span asp-validation-for="Categories">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="InformationIds"></label>
            <select asp-for="InformationIds" class="form-select" )">
                @foreach (var information in Model.Informations)
                {
                    @if (Model.PlantInformations.Any(p => p.InformationId == information.Id))
                    {
                        <option value="@information.Id" selected>@information.Key</option>
                    }
                    else
                    {
                        <option value="@information.Id">@information.Key</option>
                    }
                }
            </select>
            <div>
                <span asp-validation-for="InformationIds">
                </span>
            </div>
        </div>
        <div class="mt-2">
            <button type="submit" class="btn btn-outline-success">
                Update
            </button>
        </div>
    </form>
</div>


@section Scripts {
    <script>
        $(document).on("click", ".delete-image", function () {
            $(this).parent().remove()
        })
    </script>
}